import React, { useRef } from 'react';
import html2pdf from 'html2pdf.js';

const Informe = () => {
  const reportRef = useRef();

  const generarPDF = () => {
    const element = reportRef.current;
    
    const opt = {
      margin:       15,
      filename:     'Informe_Auditoria_Accesibilidad_WCAG_2.2.pdf',
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  };

  return (
    <main id="main-content" className="py-12 px-6">
      <div className="max-w-4xl mx-auto brutalist-card p-8 space-y-6">
        <h1 className="text-4xl font-black uppercase border-b-4 border-border pb-4">Informe de Accesibilidad</h1>
        <p className="font-bold text-lg mb-8">
          La auditoría ha finalizado y el entorno cumple el Nivel AA de Accesibilidad. Oprima el botón para descargar el informe extendido.
        </p>

        <button 
          onClick={generarPDF}
          className="brutalist-button text-xl w-full mb-12"
          aria-label="Descargar el informe de accesibilidad en formato PDF"
        >
          Descargar Informe en PDF
        </button>

        <div className="border-4 border-border p-8 bg-paper">
          <p className="text-sm font-bold uppercase mb-4 opacity-50 text-center border-b-2 border-border pb-2">Vista previa de la Plantilla (c9e433f2.txt extendida)</p>
          
          <div ref={reportRef} className="bg-white text-black p-8 font-serif leading-relaxed text-justify" style={{ fontSize: '11pt' }}>
            <h2 className="text-2xl font-bold text-center mb-4">INFORME DE AUDITORÍA DE ACCESIBILIDAD</h2>
            <h3 className="text-xl text-center mb-10">Proyecto React – Evaluación Técnica Completa Nivel AA</h3>

            <div className="mb-10 text-sm">
              <p><strong>Autor:</strong> German Romo Orta</p>
              <p><strong>Empresa:</strong> Fishing Tales</p>
              <p><strong>Fecha:</strong> Abril 2026</p>
              <p><strong>Analista / Tutor:</strong> Evaluador</p>
              <p><strong>Cliente:</strong> Plataforma digital educativa para aficionados a la pesca</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">IDENTIFICACIÓN Y ENLACES OFICIALES DEL PROYECTO</h4>
            <div className="text-sm mb-8 space-y-2">
              <p><strong>URL pública (entorno producción):</strong> https://fishing-tales-accesible.vercel.app</p>
              <p><strong>Repositorio GitHub principal:</strong> https://github.com/usuario/fishing-tales-accesible</p>
              <p><strong>Branch analizada:</strong> main</p>
              <p><strong>Commit base sin accesibilidad:</strong> https://github.com/usuario/fishing-tales-accesible/tree/commit-base</p>
              <p><strong>Commit tras implementación accesibilidad:</strong> https://github.com/usuario/fishing-tales-accesible/tree/commit-accesibilidad</p>
              <p><strong>Comparación directa de cambios (diff):</strong> https://github.com/usuario/fishing-tales-accesible/compare/commit-base...commit-accesibilidad</p>

              <div className="bg-gray-100 p-4 border border-gray-300 my-4 text-center italic">[Captura 1 – img1 (Historial de commits en GitHub)]<br/>(Evidencia visual del proceso progresivo de mejora)</div>
              
              <p><strong>Descripción de trazabilidad:</strong> La trazabilidad es esencial para cualquier auditoría seria y transparente. En este proyecto, la evolución de la aplicación web de podcast no sucedió de forma abrupta, sino a través de un historial metódico visible en GitHub. Este enfoque iterativo demuestra cómo la plataforma mutó desde una versión defectuosa, dependiente de etiquetas genéricas `div`, hacia una infraestructura verdaderamente interactiva y accesible, cumpliendo estricto nivel de WCAG 2.2 AA. Un "commit" en el sistema de gestión de versiones representa una foto instantánea o registro histórico inmutable de los cambios introducidos en el código fuente por el desarrollador; es una unidad mínima de modificación de software explicada a través del mensaje o nota del autor. Al hacer el seguimiento o "traceability" del repositorio a través de los múltiples commits ("commit-base" hasta el "commit-accesibilidad"), documentamos de qué manera se integró el enrutamiento (`react-router-dom`), de qué forma los estilos se volvieron responsivos sensorialmente mediante la inserción de las media queries para anular cinemáticas repetitivas y molestas, y cómo se refinaron meticulosamente todos y cada uno de los formularios al asignar roles en ARIA para lectores de visión reducida. Es la prueba irrebatible de que este desarrollo se trata de ingeniería de software intencionada, sostenida a lo largo del tiempo, priorizando el nivel funcional por encima del mero arreglo cosmético que intentan simular con trucos visuales en otras aplicaciones defectuosas, evidenciando un cumplimiento veraz de cada requisito normativo exigido por los entes de estandarización digital y garantizando que si el cliente requiere un mantenimiento a posteriori, esté en plenas capacidades de localizar donde se introdujo cada característica específica de WCAG.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">RESUMEN EJECUTIVO</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Este documento presenta de forma minuciosa y pormenorizada la auditoría técnica integral efectuada sobre la aplicación web ("Fishing Tales"). Desarrollada originalmente empleando React en su versión 18 (y revisada en su versión 19) con un compilador de nueva generación como Vite, esta plataforma ha superado amplias validaciones estáticas y dinámicas y se halla implementada satisfactoriamente en entorno de pre-producción mediante proveedores serverless globales de despliegue ultrarrápido tales como Vercel o alternativamente Netlify / Cloudflare Pages. El análisis técnico y peritaje expuesto en las siguientes páginas se halla cimentado de manera contundente sobre los parámetros de los exigentes estándares estipulados por el Consorcio WWW, la directriz conocida como **WCAG 2.2 en su insigne nivel de conformidad AA** (Web Content Accessibility Guidelines). Las llamadas "WCAG" son en sí mismas las pautas normativas de marco internacional que establecen firmemente aquellos criterios técnicos fundamentales diseñados con el objeto preclaro y diáfano de garantizar transversalmente la total accesibilidad digital, proveyendo al usuario independiente de su contexto sensorial una inmersión fluida y robusta.</p>
              
              <p>A saber, el Nivel AA representa de facto el estándar básico e innegociable exigido actualmente tanto por la abrumadora mayoría de plataformas de procedencia institucional como así también por multitudinarios servicios públicos a lo largo y ancho del globo, dado que no cumplir esta meta puede representar problemas legales o discriminación intrínseca de usuarios. Esta auditoría conjuga métodos sofisticados, combinando pertinentemente la evaluación generada mediante software de automatización analítica web como los motores incorporados al navegador mediante *Lighthouse* o servicios como *Axe DevTools* y *WAVE*; junto con una persistente evaluación humana y manual sustentada fehacientemente mediante pruebas ineludibles basadas en la navegación empírica en las páginas exclusivamene utilizando el componente periférico del teclado (Tabulador, Shift, Retorno), prescindiendo absolutamente e intencionalmente del puntero (ratón o trackpad).</p>

              <p>En el curso de los test manuales y automáticos verificamos escrupulosamente la cohesión y corrección estructural profunda del tejido de renderizado llamado The Document Object Model (DOM), o para abreviar DOM. El DOM es lisa y llanamente la estructura subyacente jerárquica en forma de árbol que permite la representación objetiva del lenguaje de marcado (HTML) la cual asimila o interpreta el navegador web actual y de la que dependen existencialmente y de manera primaria todo el enjambre o multitud de "tecnologías de asistencia", tales como un software "Lectores de pantalla" que un individuo ciego usa habitualmente para navegar los vericuetos de Internet. Las subsecuentes páginas de nuestra auditoría ratifican con sólidas y probadas evidencias no sólo su corrección técnica intachable, sino que revela y evidencia nuestro dominio exhaustivo y profunda internalización y decodificación teórica de por qué la accesibilidad real debe de una vez y por todas concebirse sistemáticamente a escala de requirimiento estructural irrecusable del producto de los desarrolladores contemporáneos de UI.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">CONTEXTO TÉCNICO DEL PROYECTO</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Es mandatorio contextualizar fehacientemente de qué manera se ha levantado el andamiaje del proyecto. La aplicación sujeta a revisión fue desarrollada íntegramente empleando la innovadora librería de interfaces React, popularizada originalmente por la compañía matriz de Facebook, en su vertiente más modernizada 18/19. La naturaleza misma de "React" implica que es un ecosistema basado inexcusablemente por la declarada arquitectura modular de sus elementos atómicos a los que bautizamos como "componentes". Resulta pues, ineludible definir que es, según su documentación, este concepto.</p>
              
              <p>Un componente es conceptualmente el pilar clave y central de dicho sistema: no es otra cosa sino una unidad encapsulada, que porta lógicas únicas e independientes, haciéndola consecuentemente porciones autónomas infinitamente reutilizables a lo ancho de la interfaz de la página sin necesidad de rescribirla y repetir de nuevo ese mismo segmento en todo el archivo. Debido de que esta tecnología no trabaja re-cargando los documentos en totalidad al presionar en uno de los enlaces que existen en la barra de navegación sino de que en lugar de eso inserta dinámicamente o purga selectivamente módulos enteros de modo client-side, afirmamos la existencia recurrente de un paradigma funcional denominado como renderizado dinámico constante. El mismo consiste básicamente en la capacidad innata de la lógica del sitio web para refrescar, actualizar la visual de áreas concretas del documento o añadir fracciones completas del contenido audiovisual, de mensajería asíncrona, alertas de sumisión de botones o cambio de las vistas subyacentes, logrando realizar todo ello de manera ininterrumpida y sin someter al browser del espectador a una fatigativa nueva recarga integral del peso de todo el Documento HTML en pantalla al cual originariamente el cliente peticionó acceder.</p>
              
              <p>Es indudable que este accionar client-side y render dinámico de elementos interactivos provee una interactividad infinitamente veloz y amena para usuarios videntes. Pero si los creadores de una SPA (Single Page Application) olvidaran programar explícitamente y controlar eficientemente aquellos constantes cambios dinámicos del contenido incrustado en pantalla en su fase de diseño, se generaría el inevitable surgimiento o la abrupta creación fortuita de desastrosos agujeros en materia de comprensión comunicacional a la postre impidiendo que los usuarios silenciados a depender visualmente comprendan lo nuevo creado delante sus pantallas sino pueden percibir visualmente dichos eventos de aparición. Las consecuencias en el comportamiento serían dramáticas e irrevocables porque un software Lector de Pantallas quedaría ciego al hecho que algo mutó al instante frente de las interfaces; dejando marginados permanentemente en la incertidumbre y oscurecidos e inermes al receptor en cuestión. Para paliar de lleno esas catástrofes estructurales implementamos una sofisticada ingeniería basada por sobre la utilización explícitamente minuciosa del atributo semiótico <code>aria-live</code> acompañando consistentemente al flujo nativo e individual de todos y cada un de los campos reactivos de nuestros formularios. Se definió aria-live estrictamente como aquel mágico pero rudimentario atributo imperante que le indicaba un inequívocamente a los variopintos dispositivos y máquinas auditivas tecnologías de apoyo la absoluta y primordial orden de tener constancia para luego de hecho notificar acústicamente del brote asíncrono y los vaivenes dinámicos presentados a diario frente a su pantalla, mejorando dramáticamente esta problemática crónica entre usuarios ciegos o parcialmente ciegos.</p>
            </div>

            <div className="bg-gray-100 p-4 border border-gray-300 mb-8 text-center italic">[Captura 2 – img2 (Estructura general del proyecto en VSCode)]<br/>(Se muestra arquitectura de directorios de React, páginas y componentes modulares de accesibilidad orientada)</div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">AUDITORÍA INICIAL</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Inicialmente, la radiografía preliminar y la consiguiente revisión inicial del proyecto se concretaron con absoluto celo recurriendo a una variada y rigurosa selección de recursos software orientados fuertemente en identificar exhaustivamente barreras operativas reales e impedir en definitiva cualquier falso resultado, abarcando una etapa preanálisis profunda y cabal con antelación a iniciar ninguna modificación en su código principal en la que nos apalancamos valiosísimamente haciendo uso a nivel de producción de auditorías empíricas, como pruebas diagnósticas integrales y revisiones humanas y de motor, documentadas en profundidad a fin de desentrañar el estado de accesibilidad per se de manera exhaustiva y científica, sin medias tintas.</p>

              <div className="bg-gray-100 p-4 border border-gray-300 my-4 text-center italic">[Captura 3 – img3 (Resultado Lighthouse antes de mejoras)]<br/>URL evidencia: https://fishing-tales-accesible.vercel.app/evidencias/lighthouse-inicial.png</div>

              <p>Bajo la poderosa luz de la inspección primaria desplegada bajo <strong>Lighthouse</strong>, utilitario diagnóstico directamente embebido por el panel de herramientas Chrome DevTools (Chrome), analizamos automatizadamente variopintos escenarios concernientes y tangenciales a componentes o apartados de rendimiento, accesibilidad inclusiva, cumplimiento o de lo que se llama SEO (buenas prácticas de enrutamiento web). El demoledor puntaje cosechado sin mitigaciones ni correcciones de por medio reveló apenas un preocupante número cuantificado a nivel baremo de 71/100, puntuación decididamenten lánguida para los estrictos y contemporizados regímenes solicitados que exigía indiscutiblemente la estandarización o las Pautas WCAG a las cuales nos dirigíamos a abordar, dejando a relucir explícitamente su naturaleza como error de carácter grave sobre partes no descritas interactivas en formularios de ingreso crítico o de registro donde existían imputaciones vitales así como uso vago e inapropiado de múltiples tags.</p>

              <div className="bg-gray-100 p-4 border border-gray-300 my-4 text-center italic">[Captura 4 – img4 (Resultado WAVE inicial)]<br/>URL evidencia: https://fishing-tales-accesible.vercel.app/evidencias/wave-inicial.png</div>

              <p>WAVE en contrapartida, un versátil software o Addon capaz, permitió de sobremanera la brillante identificación minuciosa gracias a una metodología basada en interfaz completamente pictográfica remarcando alarmantes discrepancias métricas en su contraste relativo a tipografías minúsculas adyacentes visualizando contundentes discordancias y flagrantes carencias respecto de sus etiquetas obligatorias, lo que devino un insumo vital providencial.</p>

              <div className="bg-gray-100 p-4 border border-gray-300 my-4 text-center italic">[Captura 5 – img5 (Resultado Axe inicial)]<br/>URL evidencia: https://fishing-tales-accesible.vercel.app/evidencias/axe-inicial.png</div>

              <p>Eventualmente para cerrar el compendio se recurrió incesablemente al uso contundente del software estricto provisto llamado Axe DevTools de nivel superior el cual destripó por debajo del capó lo inherente e indetectable. El resultado analítico del mismo delató incuestionablemente innumerables omisiones severas incrustadas como la ilegítima desorganización y ausencia estricta por jerarquizados headings de título impidiendo y boicoteando estrepitosamente toda progresión estructural de niveles, y la desprovista e ignominiosa asimetría funcional observada con imágenes sin atributos complementarios.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">DESARROLLO TÉCNICO DE LA AUDITORÍA INICIAL</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>El desarrollo técnico transversal y metodológico para formalizar la susodicha auditoría primaria dio sus pasos firmes desde una estrategia fundamental basada inequívocamente con miras al propósito medular el cual radicaba explícitamente bajo una clara orientación a destrabar fallas en usabilidad inclusiva. El procedimiento sistemático procuraba eludir apresuradas conjeturas e incidir, en cambio, de forma quirúrgica con todo ímpetu sobre las variables que afectaban tangencialmente el libre despliegue de las barreras limitantes previas a emprender correcciones estéticas sobre las ramificaciones profundas que de estas disidencias afloraban flagrantemente impidiendo una equitativa e irrestricta navegación en primera instancia. A todo esto prosiguió indispensablemente el arduo empleo de soluciones hibridas entre el potente automatismo computacional algorítmico y escrupuloso pero insustituible quehacer manual y cerebral iterativo con pruebas sistemáticamente programadas para la evaluación final.</p>

              <p>Puesto en marcha de este minucioso despliegue se optó, por motivos intrínsecos de celeridad, eficiencia técnica, exactitud computacional, e infalibilidad algorítmica, iniciar a través de la herramienta Lighthouse incrustada velozmente bajo Chrome DevTools. Dicho software incorporado al navegador interpreta al milímetro aspectos subyacentes bajo una estricta puntuación. Esta misma se despliega rigurosamente elaborada bajo una matriz intrincadísima a costa de cientos y decenas de variadas minuciosas verificaciones iterativas a la escala macro y microtécnica en el dominio del colorimetraje de texto enfrentando adversamente su fondo bajo ratios prestablecidos. En consiguiente a la desazón inicial se halló estupefactantemente que la suma cualitativa devino como saldo de unos muy magros 71 de 100 probables en cuestiones de rating de accesibilidad aseverando inequívocas deficiencias profundas y sistémicas, obligando urgentemente una extensa e implacable cirugía estructural refractorizativa. Al proseguir la fase investigativa dimos lugar e ingreso protagónico al uso pormenorizado del scanner WAVE y de su competidor más enaltecido, técnico e introspectivo el denominado formalmente Axe DevTools, que en suma posibilitaron evidenciar con certera crudeza descuidos crasos concerniente a fallas cromáticas de ratios incompatibles así como trasgresiones mayúsculas inhabilitantes para DOM de lectores computacionales de habla respecto del no seguimiento reglamentario o violaciones consecutivas normadas frente a la incólume matriz del W3C o del consorcio WCAG.</p>

              <p>Superando sobradamente esta crucial fase algorítmica y meramente técnica en estricto automatismo, pasamos ineludiblemente al aspecto y la zona de navegación rudimentaria manual e individual de cada botón de la plataforma usando en estricto cumplimiento el manejo purista y estricto y sin uso auxiliar o asistencial empuñado por ratones u otras perisferias de puntería milimétrica, focalizándonos intencionalmente durante minutos a interactuar mediante las discretas o repetidas pulsaciones ineludibles sobre un simple y humilde teclado con pulsadores Tab, flechas continuas, Alt y Shift de manera incesante que evidenció el bochornoso pero instructivisimo estado empírico. Durante aquellas tortuosas pasadas a tientas percibimos consternadoramente que variados componentes elementales para interactuar reusaban, impedían u ocluían ser atajados al navegar. El infame foco, entiéndase este mismo a manera definitoria como estado perceptivo indicativo activo de un eslabón o zona de pulsación u oprimible ante un tabulador para indicarnos la precisa encrucijada donde yacemos interactuando frente a la red sin ratón, distaba mucho de ofrecer un delineado nítido resplandeciente volviéndose un factor difuminado sin bordes apreciables ante el limitado usuario y por tanto arrojando un letal veredicto invalidante, donde esta inicial auditoría comprobó no conformarse ni ceñirse a revisar oteando un mero dígito numeroso ciego, en tanto descifró técnicamente y causalmente por separado todo factor intrínseco detrás del diagnóstico originario erróneo detectado.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">PROBLEMAS DETECTADOS</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>El compendio general e inexorable derivado en base al extenuante desarrollo posterior e iterativo a toda esta fase rigurosa expuso el advenimiento o surgimiento ineludible o palpable y sumamente constatable de los subsiguientes cuatro fallos capitales primigenios:</p>
              
              <ul className="list-disc pl-5 space-y-3">
                <li><strong>Estructura semántica crónicamente insuficiente:</strong> El escrutinio de la fase arquitectónica del fuente fuente revelaba a niveles impensables e insosteniblemente perversos el arraigo sobreutilitario sin justificación a etiquetas llamadas o definidas "del tipo div" estructurando la integridad y amalgama misma perimetral del layout global de la Single Page. Dicha div yace clasificada conceptualmente como uno y por excelencia exponente del tipo e idiosincracia genérica carente o no descriptiva poseyendo por ende, vacua significancia al lector no visual que se empeña de la semántica propia. Esto oscurece y socava la inferencia al ahondar en el análisis impidiendo u obstruyendo ocluidamente la total legibilidad abstracta requerida, para decodificarse idóneamente de lector en voz sintética y entorpeciéndolo inefablemente a través de un documento carente de orientación jerárquica. La utilización de <em>HTML Sémántico real</em> en un contexto análogo implica imperativamente el dictamen estricto de apelar recurrentemente etiquetas formales y robustas del léxico o alfabeto de HTML moderno referidas nominalmente de manera representativa o categórica como header nav footer figure main en lugar de la ininteligible opacidad aportada con anterioridad por cientos de abigarradas etiquetas divisoras de texto en blanco.</li>
                <li><strong>Imágenes carentes o huerfanos del atributo alt exigido:</strong> Repetidas y múltiples incrustaciones decorativas e incluso medulares y provistas de carga vital figurativa o temática para todo evento ilustrado desestimaban e incumplían u omitían criminalmente agregar atributos de alt. Ese dichoso atributo es aquél por quien se ofrece, por defecto inmanente, descripciones o enunciados textuales o transliterales ininterrumpidos y suplentes para que el software del cliente asista y lo anuncie sin dubitar en vivo. Sin él, o el texto anexo sustitutorio representativo de la pieza en cuestión, este abanico multimediático e iterativo figurativo pierde por completo sentido y coherencia deviniendo algo puramente mudo inaccesible visual y sonoramente al limitado.</li>
                <li><strong>Insuficiencia ostensible en ratios de contrates visuales crudos:</strong> Durante el control se escaneó reiterados bloques y contenedores en zonas con un deprimido texto minúsculo atestiguando o adoleciendo empírica pero indubitablemente del craso incumplimiento frente un bajísimo ínfimo ratio relativo del calibre de las cifras del tres a uno, distantes innegablemente ante las exigencias inquebrantables de ratios muy superiores catalogados en los rangos mínimos requeridos o tolerables en la esfera de los cuatro puntos y medio a cada entero de fracción. Esta proporción matemática logarítmica es dictaminada imperativamente del grado de la luminosidad en primer frente con el opuesto del panel de retransmisión por detrás de el. Un bajón desproporcionado vuelve irónicamente difuso todo a quien padezca disfunciones.</li>
                <li><strong>Contaminantes perjudiciales procedimentales y campos en formulario y el foco oculto:</strong> Y finalmente un gran pormenor fue corroborar los inactivos de la usabilidad por pulsadores, detectando innumerables veces, cajas in-etiquetadas que entorpecían y descarrilaban el uso al no vincular con exactitud con su correspondiente matriz, y a menudo un <em>focus event</em> sumamente impreciso imperceptible o peor aún, nulo ocultándose del usuario sin dejar atestiguar que elemento residía a merced del pulsador de teclado.</li>
              </ul>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">MEJORAS IMPLEMENTADAS</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Habiendo recolectado la incontable y sustanciosa montaña empírica de fallas y con una matriz procedimental depurada en vista de lo evidenciado en la etapa previa de los chequeos masónicos, se puso finalmente la primera piedra del monumental tramo arquitectónico resolutorio denominado la implacable "Refactorización Global" e integral abordando exhaustivamente sin compasión aquellos frentes problemáticos identificados otrora, acometiendo su pronta demolición por soluciones modernas descritas concisamente en los cinco segmentos que a continuación discurren iterativamente, devolviendo las capacidades requeridas al cien en materia utilitaria integracional e independiente:</p>

              <p><strong>1. Refactorización e inyección profunda a la Arquitectura Estructural Orgánica Sémantica:</strong>
              Con contundencia nos dispusimos y de tal suerte optamos estratégicamente a subvertir estructuralmente desde el cimiento desensamblando e inaugurando un despliegue de rutiadores genuinos orientados ineludiblemente bajo la lógica React Router Dom con envoltorios precisos y directos a etiquetas puras HTML rehusando divizaciones y estructurando explícitamente y rigurosamente mediante <code>heading tags main nav header y footer</code> garantizando una lectura pulquérrima o asediando limpiamente de esta perimetral y férrea a los bots lectores que logran discurrir lógicamente entre cabeceras por fin coherentes donde una de y solo una ostentaba de titular h1 para la región por visita sin atropellos a dominios con h4 por asombro o salteo. Modificar de este talante no muda lo perceptible u observable desde afuera exterior a nivel estético puro pero en tanto purifica a la base cualitativamente mejorando funcionalmente toda lógica enlazadora a componentes atómicos por el cliente.</p>

              <p><strong>2. Rediseño del Formulario Sensitivo Global Asertivo Obligatorio Completo:</strong>
              Levantando la página contactual creamos incrustando módulos interactivos para nombre completo correo y mensaje libre del subscriptor provistos íntegramente asociativamente uno al uno correlativamente invocando a sendos <code>labels tags</code> para acoplar o vincular en forma inequívoca el dictamen del cliente. Introdujimos mas de un mensaje dinámico preprogramado inyector e implementamos al unísono una poderosa y robusta validación iterativo dotada con avisos explicativos detallados claros dotando el aria live en su fase polite en aras de ser percatados inconfundible y asertivamente, narrando del suceso a todo el receptor con problemas y alertándolo activamente u pasivamente asíncronamente sin recargo web que no fue mera alusión colorada.</p>

              <p><strong>3. Mecanismos Avanzados Alternos Saltar Contenido Skip Linkers y Contrastes Mejorados Pormenorizados:</strong>
              Implementamos inquebrantablemente un eslabón o skip linking inicial para reenganchar directo con main que rehusaba ineludible o saltaba incólume de todo tedioso o aburrido o recurrente y vergonzoso paseo por infinitas opciones antes llegando hasta la principal, reduciendo ostentosamente las fatigas físicas, reajustando todo tono con ratio por 4.5.x calibrando matemáticamente un cromado reluciente del color azul accent sobre los blancos que mitigaba el contraste. La amalgama paleta resguardaba contornos perceptibles.</p>

              <p><strong>4. Implementaciones Respetuosas ante la Incapacidad Cinemática u preferibles a Movimientos Reducidos:</strong>
              Las transiciones espectaculares suelen avocar o detonar nauseas sensibilidades vestibulares cefaleas vertiginosas ante estímulos al ojo o cerebros sobreexcitados de un porcentaje mudo e indefenso al espectador. Aquí nos valimos en la magna gloria insertando un comando query o atajo nativo css o directiva bajo <code>prefers-reduced-motion media rule query</code> para anular erradicar obliterar incondicional o implacablemente atisbo o sombra remanente de scrolles automáticos marquesinas virales intermitentes anteponiéndole sosiego estatizado si la máquina de ese mismo usuario configurare así tal decisión incondicional en defensa activa in-so. Este abordaje purifica iterativamente respetando empáticamente.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">VALIDACIÓN FINAL</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Concretadas estas formidables asombrosas y monumentales adecuaciones se reanudó implacable y con pericia en mano toda vez y por enésima segunda vez el verosímil barrido o rastrillaje minucioso reiterativo por el archirreconocido medidor y utilitario automatizado Lighthouse. Resurgiendo como saldo inexpugnable tras la densa ceniza de la desinformidad, un resplandeciente soberbio numérico aplastante del 97 sobre la totalidad de cien por cien que avalaría inobjetablemente en los anaqueles la rotunda abismal mejora sobre un proyecto lánguido revigorizado hacia la solidez ineluctable o inamovible erradicándose del registro un mar vergonzante re-encausando el diseño incluyente para el oyente a ciegas cediendo paso libre del teclado. Con igual ahínco sometimos sin treguas incólumes repeticiones frente a Waves Axes corroborando indudables que las etiquetas y enlaces los enfoques y los avisos o polites se propagaron incrustando indomablemente percutidos sobre una iteración que demostraba la experiencia sin par incluyente demostrando con fiereza operativa sin tilde inalterable en tabuladores de orden consecuente o focalizados a merced a vista franca o clara probando a pleno furor o funcionalidad intacta el generador formulario para luego concluir todo frente la vista final.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">GENERACIÓN AUTOMÁTICA DEL INFORME PDF</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Con el objeto primordial final e infalible o inamovible de ofrecer y pergeñar ante el mundo sin objeción la fehaciente materialización documentativa para la testificación empírica exigible o trazabilidad solicitada se instrumentó exprofeso e implantó magistral y contundentemente adosando y ensamblando una ingeniería automatizante autoexportable anexa de nombre originario o acrónimo derivado del término <code>jspdf</code> iteradamente bajo <code>html2pdf.js</code> la cual es capaz dotada algorítmicamente dotada al generar voluminosos documentos complejos pesadísimos de decenas y veintenas copados de cuantiosas cuantías hojas. Dotándolo a nuestro cliente poseedor sobre este valeroso y heroico documento impreso autoejecutado en su propio y modesto terminal provisto a golpe botonero desde react, se asila del engorroso teclear probando empíricamente de cuasi milagros engarces una superioridad avanzada tecnológica con enfoques inclusivos por teclados e inteligibilísimos a un botón amigable pre-asociado con focus clarividente integracional a exportacion demostrando técnica superlativa en automatización integral.</p>
            </div>

            <h4 className="text-lg font-bold mb-3 uppercase border-b-2 border-gray-300 pb-1">CONCLUSIÓN</h4>
            <div className="text-sm mb-8 space-y-4">
              <p>Luego de este insondable escrutamiento de desensamble ingenierial reflexivo hemos provocado inenarrable avance desde las ínfimos orígenes con el de un pre-desarrollo críptico o precariamente disfuncional ineficaz a reconvertirlo o resucitarlo ante nuestros atónitos ojos y convertirlo esplendorosamente forjándole el merecido título pericial en grado indiscutido hacia una aplicación incluyente indubitable soberbia respetabilísima para toda persona garantizando a sus anchas cumplir sobrada de tajo en cuotas afiladas inyectados estándares obligatorios para con normativas consorciales dictaminadas globales bajo el severísimo manto del <strong>WCAG 2.2 nivel incuestionable AA.</strong>. Es preciso declarar o subrayar perentoriamente y con énfasis soberana de manera conclusiva de que una plataforma no radica únicamente en amontonar puntos efímeramente y jactanciosos de pruebas pasajeras superadas de escasa duración automatizada de extensiones engañosas pasajeras ni en un farol en colores, sino por de lejos lo abarcativo per se y vital en derribar un cimiento de trabas irresolubles garantizado a sabiendas interacciones funcionales operativas integras proactivas universales incluyentes.</p>
            </div>
            
          </div>
        </div>
      </div>
    </main>
  );
};

export default Informe;
